### ISSUE TITLE
[Skript] condition . if item is stackable

### ISSUE THREAD

**Issue by cooffeeRequired** [SkriptHub/SkriptHub#101]
**Hello there,**
*I basically write this condition for check if item is `stackable`*, we'll be honest if you add it

```hs
condition ([the] [item] %item% is stackable):
	check:
		max stack size of (expr-1) > 1:
			continue
````

**Comment by eyesniper2** [comment]
I might be misinterpreting this, but are you look to have this added to Skript?

If you are, you will want to make a feature request here: https://github.com/SkriptLang/Skript since they are the ones the write Skript, this issue tracker is just for the website Skript Hub.
