### ISSUE TITLE
Wont let me upload a sciprt

### ISSUE THREAD

**Issue by 1-x409** [SkriptHub/SkriptHub#105]

**Comment by eyesniper2** [comment]
Hey 1-x409,

Sorry about the delay in getting to this ticket. Can you please provide me with screenshots around what you are seeing on your end and a copy of your script so I can see what's going wrong? You can post them either here or send them to be via discord to eyesniper2#0001.

Thanks!

**Comment by 1-x409** [comment]
its fixed.
