### ISSUE TITLE
New Addon

### ISSUE THREAD

**Issue by TrasonCo** [SkriptHub/SkriptHub#107]
Skript Hub Username: trason
Addon name: Skitch
link to addon: https://github.com/TrasonCo/Skitch

**Comment by TrasonCo** [comment]
[Skitch Docs.zip](https://github.com/SkriptHub/SkriptHub/files/9842090/Skitch.Docs.zip)

**Comment by eyesniper2** [comment]
Awesome! Skitch has been added to your account!
