### ISSUE TITLE
New Addon

### ISSUE THREAD

**Issue by AydenC77** [SkriptHub/SkriptHub#115]
Skript Hub Username: AydenC77
Addon name:  Skript-License
link to addon: https://github.com/AydenC77/Skript-License/releases

**Comment by eyesniper2** [comment]
Hey @AydenC77,

It looks like from the release page that you are making a script, not an addon. The good news is that Skript Hub supports both! If you go [here](https://skripthub.net/scripts/) and click the create button in the top right, you should be able to upload your script and share it that way,

Let me know if you have any questions!
