### ISSUE TITLE
New Addon

### ISSUE THREAD

**Issue by feeeedox** [SkriptHub/SkriptHub#116]
Skript Hub Username: fedox6
Addon name: skCord
link to addon: https://www.spigotmc.org/resources/skcord-send-discord-webhooks.106832/

im working on updates in the next few days

**Comment by eyesniper2** [comment]
Hey Fedox-die-Ente, 

Sorry about the delay. For adding addons to Skript Hub we typically want to see addons that have more then 1 syntax element. Once you have a few more syntax elements added, feel free to open another ticket and we will get it added!
