### ISSUE TITLE
fix new style

### ISSUE THREAD

**Issue by FUZIK** [SkriptHub/SkriptHub#12]
angles - not cool
![image](https://user-images.githubusercontent.com/15977008/39422522-90f3b8c4-4c22-11e8-9d60-faf64889f33a.png)

**Comment by eyesniper2** [comment]
Hello FUZIK,

Thanks for the feedback on the UI. After talking with a few other users and site staff about the new style for the site, we have decided that we are not going to use rounded corners for the syntax element boxes.

Thanks again for the feedback!
