### ISSUE TITLE
set compass target

### ISSUE THREAD

**Issue by AbadyElad** [SkriptHub/SkriptHub#147]
Hi, i'm trying to make somthing with my compass
but every time i set the compass a taget it automaticlly set to every compass targer of player to the target i just set
here is the code `set compass target of player to location of arg-2` arg-2 is a player
the goal is to set the target of player's tool sepertly from any other compass

**Comment by eyesniper2** [comment]
Hey AbadyElad,

This issue tracker is for the Skript Hub website and not for Skript it's self. If you are looking for Skript help, asking for help in our [discord](https://skripthub.net/discord/) is going to be the best place.
