### ISSUE TITLE
Variables wont save to variables.csv

### ISSUE THREAD

**Issue by SCoop1000** [SkriptHub/SkriptHub#152]
Hello, I'll post my script below, and as the title says, no variables will save if I shut down the server. I even included /save-all commands to try and fix this.

`
# Faction Management Command
command /faction <text> [<text>]:
    description: Manage your faction.
    usage: /faction help, /faction create <name>, /faction delete <name>, /faction invite <player>, /faction join <name>, /faction leave, /faction list, /faction claim, /faction unclaim, /faction power
    permission: skript.example.faction
    executable by: players
    trigger:
        if arg-1 is "help":
            send "&6&lFaction Commands:" to player
            send "&e/faction help &7- &fDisplay all faction commands." to player
            send "&e/faction create <name> &7- &fCreate a faction with the specified name." to player
            send "&e/faction delete <name> &7- &fDelete your faction." to player
            send "&e/faction invite <player> &7- &fInvite a player to your faction." to player
            send "&e/faction join <name> &7- &fJoin a faction with the specified name." to player
            send "&e/faction leave &7- &fLeave your current faction." to player
            send "&e/faction list &7- &fList all members of your faction." to player
            send "&e/faction claim &7- &fClaim the chunk you are standing on for your faction." to player
            send "&e/faction unclaim &7- &fUnclaim the chunk you are standing on." to player
            send "&e/faction power &7- &fView your power and your faction's power." to player
        else if arg-1 is "create":
            if arg-2 is set:
                if {faction::%arg-2%::leader} is not set:
                    set {faction::%arg-2%::leader} to uuid of player
                    set {player::%uuid of player%::faction} to arg-2
                    set {player::%uuid of player%::power} to 10
                    execute console command "/save-all"
                    send "Faction <green>%arg-2%<reset> created successfully!" to player
                else:
                    send "A faction with the name <green>%arg-2%<reset> already exists." to player
            else:
                send "You must specify a name for the faction." to player
        else if arg-1 is "delete":
            if arg-2 is set:
                if {faction::%arg-2%::leader} is uuid of player:
                    delete {faction::%arg-2%::*}
                    loop all players:
                        if {player::%uuid of loop-player%::faction} is arg-2:
                            delete {player::%uuid of loop-player%::faction}
                    execute console command "/save-all"
                    send "Faction <green>%arg-2%<reset> has been deleted." to player
                else:
                    send "You are not the leader of faction <green>%arg-2%<reset>." to player
            else:
                send "You must specify the name of the faction to delete." to player
        else if arg-1 is "invite":
            if arg-2 is set:
                if {player::%uuid of player%::faction} is set:
                    if {faction::%{player::%uuid of player%::faction}%::leader} is uuid of player:
                        set {_target} to arg-2 parsed as player
                        if {_target} is online:
                            set {faction::%{player::%uuid of player%::faction}%::invites::%uuid of {_target}%} to true
                            execute console command "/save-all"
                            send "You have invited <green>%arg-2%<reset> to join your faction." to player
                            send "You have been invited to join the faction <green>%{player::%uuid of player%::faction}%<reset>. Type /faction join %{player::%uuid of player%::faction}% to accept." to {_target}
                        else:
                            send "Player <green>%arg-2%<reset> is not online." to player
                    else:
                        send "You are not the leader of your faction." to player
                else:
                    send "You are not part of any faction." to player
            else:
                send "You must specify a player to invite." to player
        else if arg-1 is "join":
            if arg-2 is set:
                if {faction::%arg-2%::leader} is set:
                    if {faction::%arg-2%::invites::%uuid of player%} is set:
                        set {player::%uuid of player%::faction} to arg-2
                        delete {faction::%arg-2%::invites::%uuid of player%}
                        execute console command "/save-all"
                        send "You have joined the faction <green>%arg-2%<reset>." to player
                    else:
                        send "You have not been invited to join the faction <green>%arg-2%<reset>." to player
                else:
                    send "Faction <green>%arg-2%<reset> does not exist." to player
            else:
                send "You must specify the name of the faction to join." to player
        else if arg-1 is "leave":
            if {player::%uuid of player%::faction} is set:
                set {_faction} to {player::%uuid of player%::faction}
                delete {player::%uuid of player%::faction}
                execute console command "/save-all"
                send "You have left the faction <green>%{_faction}%<reset>." to player
            else:
                send "You are not part of any faction." to player
        else if arg-1 is "list":
            if {player::%uuid of player%::faction} is set:
                set {_faction} to {player::%uuid of player%::faction}
                send "Members of <green>%{_faction}%<reset>:"
                loop all players:
                    if {player::%uuid of loop-player%::faction} is {_faction}:
                        send "- <yellow>%loop-player%<reset>" to player
            else:
                send "You are not part of any faction." to player
        else if arg-1 is "claim":
            if {player::%uuid of player%::faction} is set:
                set {_faction} to {player::%uuid of player%::faction}
                set {_chunk} to "%chunk at player%"
                if {faction::claimed::%{_chunk}%} is not set:
                    set {faction::claimed::%{_chunk}%} to {_faction}
                    execute console command "/save-all"
                    send "You have claimed this chunk for your faction." to player
                else:
                    send "This chunk is already claimed by <green>%{faction::claimed::%{_chunk}%}%<reset>." to player
            else:
                send "You are not part of any faction." to player
        else if arg-1 is "unclaim":
            if {player::%uuid of player%::faction} is set:
                set {_faction} to {player::%uuid of player%::faction}
                set {_chunk} to "%chunk at player%"
                if {faction::claimed::%{_chunk}%} is {_faction}:
                    delete {faction::claimed::%{_chunk}%}
                    execute console command "/save-all"
                    send "You have unclaimed this chunk for your faction." to player
                else:
                    send "This chunk is not claimed by your faction." to player
            else:
                send "You are not part of any faction." to player
        else if arg-1 is "power":
            if {player::%uuid of player%::power} is set:
                send "Your current power is <green>%{player::%uuid of player%::power}%<reset>/10." to player
            else:
                send "You have no power data." to player
            if {player::%uuid of player%::faction} is set:
                set {_faction} to {player::%uuid of player%::faction}
                set {_totalPower} to 0
                loop all players:
                    if {player::%uuid of loop-player%::faction} is {_faction}:
                        add {player::%uuid of loop-player%::power} to {_totalPower}
                send "The total power of your faction <green>%{_faction}%<reset> is <green>%{_totalPower}%<reset>." to player
            else:
                send "You are not part of any faction." to player
        else:
            send "Correct usage: /faction help, /faction create <name>, /faction delete <name>, /faction invite <player>, /faction join <name>, /faction leave, /faction list, /faction claim, /faction unclaim, /faction power" to player

# Power Mechanics
every 1 hour:
    loop all players:
        if {player::%uuid of loop-player%::power} < 10:
            add 1 to {player::%uuid of loop-player%::power}
            execute console command "/save-all"
            send "You have gained 1 power. Your current power is now % {player::%uuid of loop-player%::power}%/10." to loop-player

on death:
    victim is a player
    remove 2 from {player::%uuid of victim%::power}
    if {player::%uuid of victim%::power} < 0:
        set {player::%uuid of victim%::power} to 0
    execute console command "/save-all"
    send "You have lost 2 power. Your current power is now % {player::%uuid of victim%::power}%/10." to victim

# Territory Protection
on player move:
    set {_chunk} to "%chunk at player%"
    if {faction::claimed::%{_chunk}%} is set:
        set {_faction} to {faction::claimed::%{_chunk}%}
        if {player::%uuid of player%::faction} is not {_faction}:
            if {player::currentChunk} is not {_chunk}:
                send title "&cEntering Territory" with subtitle "&a%{_faction}%" to player
                set {player::currentChunk} to {_chunk}
    else:
        if {player::currentChunk} is set:
            send title "&cLeaving Territory" with subtitle "&a%{player::currentChunk}%" to player
            delete {player::currentChunk}

on block break:
    set {_chunk} to "%chunk at player%"
    if {faction::claimed::%{_chunk}%} is set:
        set {_faction} to {faction::claimed::%{_chunk}%}
        if {player::%uuid of player%::faction} is not {_faction}:
            cancel event
            send "You cannot break blocks in the territory of <green>%{_faction}%<reset>." to player

on block place:
    set {_chunk} to "%chunk at player%"
    if {faction::claimed::%{_chunk}%} is set:
        set {_faction} to {faction::claimed::%{_chunk}%}
        if {player::%uuid of player%::faction} is not {_faction}:
            cancel event
            send "You cannot place blocks in the territory of <green>%{_faction}%<reset>." to player

on inventory click:
    set {_chunk} to "%chunk at player%"
    if {faction::claimed::%{_chunk}%} is set:
        set {_faction} to {faction::claimed::%{_chunk}%}
        if {player::%uuid of player%::faction} is not {_faction}:
            cancel event
            send "You cannot access inventories in the territory of <green>%{_faction}%<reset>." to player

# Force save Skript variables every 5 minutes
every 5 minutes:
    execute console command "/save-all"

`

**Comment by SCoop1000** [comment]
Don't know how I messed up the code formatting... sorry

**Comment by eyesniper2** [comment]
Hey @SCoop1000,

This issue tracker is for the Skript Hub website and not for Skript it's self. For Skript issues, you should report them to the [Skript Lang GitHub](https://github.com/SkriptLang/Skript) issue tracker.
