### ISSUE TITLE
SkEssentials

### ISSUE THREAD

**Issue by EquipableMC** [SkriptHub/SkriptHub#159]
Skript Hub Username: Equip
Addon name: SkEssentials
link to addon: [Github](https://github.com/EquipableMC/SkEssentials)

**Comment by eyesniper2** [comment]
Hey @EquipableMC,

Has this addon been released publicly yet? We typically don't add addons to Skript Hub until they are available for download on places like GitHub, Spigot etc.

**Comment by EquipableMC** [comment]
> Hey @EquipableMC,
> 
> 
> 
> Has this addon been released publicly yet? We typically don't add addons to Skript Hub until they are available for download on places like GitHub, Spigot etc.

Hello! I wanted to get the docs situated first before I posted a release. 

Edit: I got it on SkUnity Docs (for now) so I will post a release (which is now posted)

**Comment by eyesniper2** [comment]
Awesome! SkEssentials has been added to your account!
