### ISSUE TITLE
New Addon

### ISSUE THREAD

**Issue by DjDisaster** [SkriptHub/SkriptHub#163]
Skripthub Username: djdisaster
Addon name: SkDisaster
Link to download: https://github.com/DjDisaster/SkDisaster/releases/latest

Also if possible could you please remove 'SkriptDisplays' and 'SkHoneybee' from my account, those are addons that no longer work and aren't updated.

**Comment by eyesniper2** [comment]
Awesome! SkDisaster has been added to your account!

I have also removed SkriptDisplays and SkHoneybee from Skript Hub.
