### ISSUE TITLE
Use verbs in menu bar

### ISSUE THREAD

**Issue by lelandjansen** [SkriptHub/SkriptHub#26]
`s/Login/Log In/` and `s/Signup/Sign Up/` in the menu bar.

In the menu bar, "log in" and "sign up" are verbs (actions) and therefore should be written with a space. "Login" and "signup" (no space) are nouns. E.g. "Go to the *login* page to *log in*."

![image](https://user-images.githubusercontent.com/11789857/53527441-3208dd00-3aa4-11e9-80f9-fdcbd5a9eb75.png)

**Comment by eyesniper2** [comment]
Thanks for the heads up! I have gone and fixed up that wording!
