### ISSUE TITLE
Cannot make arguments for commands

### ISSUE THREAD

**Issue by ToolkitGaming** [SkriptHub/SkriptHub#30]
I can't make any arguments for custom commands.

Every time I make an argument such as `/example <text>`, or `/example [<text>]`, when I reload all scripts, it says it reloaded the scripts properly, but it also says "An internal error occurred while attempting to perform this command", or something like that. When I try to use the command, it doesn't work at all. Anyone else know how to fix this?

**Comment by Blueyescat** [comment]
Hello, this issue tracker is used for website related issues. Please come to our Discord server for general Skript help: https://discord.gg/phpWHGU

**Comment by ToolkitGaming** [comment]
Dude not everyone has Discord, like me

**Comment by Blueyescat** [comment]
Discord is a good app and is where you can get the fastest and the best Skript help, why not make an account? You can use it in your web browser. There is also skUnity forums, but it also requires an account. There is no a GitHub repository for Skript help.
