### ISSUE TITLE
New Addon - SkBee

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptHub/SkriptHub#37]
Skript Hub Username: ShaneBee
Addon name: SkBee
link to addon: https://www.spigotmc.org/resources/skbee.75839/

I know what you're thinking "Oh man ShaneBee, ANOTHER addon?"
But .... SkBee joins Sk-NBeeT, SkBoard and SkRecipe all in one. Those 3 addons will be deprecated and removed in the future :)
#Condensing

**Comment by eyesniper2** [comment]
All good! SkBee has been added to your account!
