### ISSUE TITLE
New Addon - skript-placeholders

### ISSUE THREAD

**Issue by APickledWalrus** [SkriptHub/SkriptHub#39]
Skript Hub Username: APickledWalrus (I signed up w/ discord - if that's an issue lmk :))
Addon name: skript-placeholders
link to addon: https://github.com/APickledWalrus/skript-placeholders

This addon is a fork of Ersatz, but the PAPI hook as been updated, some syntax changed, and support for MVdWPlaceholderAPI was added.

Thanks!

**Comment by eyesniper2** [comment]
Awesome! skript-placeholders has been added to your account!
