### ISSUE TITLE
New Addon - SkDynmap

### ISSUE THREAD

**Issue by Skylyxx** [SkriptHub/SkriptHub#44]
Hi, I would like to add **SkDynmap** to SkriptHub's documentation.

**Skript Hub Username:** Skylyxx (registered with Discord)
**Addon name:** SkDynmap
**Link to addon:** [https://github.com/Skylyxx/skdynmap/](https://github.com/Skylyxx/skdynmap/)

**SkDynmap** is an addon that allows you to create colored areas on the map, with more features to come.

Thanks !

**Comment by eyesniper2** [comment]
Awesome! SkDynmap has been added to your account!
