### ISSUE TITLE
Remove some addons

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptHub/SkriptHub#47]
Hello

Could you please remove the following addons from the docs/My profile:
- Sk-NBeeT
- SkBoard
- SkRecipe

These 3 addons were merged into SkBee quite some time ago, and are no longer needed. They're also confusing to people who stumble across them, thinking they're still valid addons.

Thank you kindly
- ShaneBee 👍

**Comment by Ignited550** [comment]
man these have been on the docs forever and skripthub still won't bother to get rid of them, you can try editing all of them or editing all the examples saying that these are deprecated and just to use skbee

**Comment by eyesniper2** [comment]
Sorry about this, I during this time I got distracted by some work stuff and it fell off my radar and got buried in my inbox. I have removed the three other addons from SkriptHub. Thanks for bumping the issue.
