### ISSUE TITLE
New Addon - SkUtils

### ISSUE THREAD

**Issue by ItsTheSky** [SkriptHub/SkriptHub#50]
Hi, I would like to add SkUtilsto SkriptHub's documentation.

Skript Hub Username: SkyCraft78 (registered with Discord)
Addon name: SkUtils
Link to addon: 

- GitHub : https://github.com/Skycraft78/SkUtils
- Documentation : https://itsthesky.info/addons/skutils/
- Release : https://github.com/SkyCraft78/SkUtils/releases

SkUtils is an addon which allow player interact with other Plugins, which they are actually: 

- MMOItems
- aSkyBlock
- DeluxeBazaar
- NoteBlockAPI
- UltraSkyBlock-Core

Thanks !

**Comment by eyesniper2** [comment]
Awesome! SkUtils has been added to your account!
