### ISSUE TITLE
New Addon - SkImage

### ISSUE THREAD

**Issue by ItsTheSky** [SkriptHub/SkriptHub#52]
Hello !
New addon, which will repace SkUtils soon.
SkImage allow you to make, edit and save custom image with Skript.
It will be very usefull for vixio (Discord) and (soon) for skript-frame which interact with minecraft maps.
My skripthub username is SkyCraft78

**Links**
GitHub - https://github.com/SkyCraft78/SkImage
Release - https://github.com/SkyCraft78/SkImage/releases

Thanks and have a good day ;)

**Comment by eyesniper2** [comment]
Awesome! SkImage has been added to your account!

**Comment by PolsatGraniePL** [comment]
WOW
