### ISSUE TITLE
NewAddon - skScraft (Bungee Syntaxes for Skript)

### ISSUE THREAD

**Issue by scraft-official** [SkriptHub/SkriptHub#53]
Hi, i have made a Skript Addon, that hooks into BungeBridge, and I add some most important BungeeCord syntaxes. This plugin is very ligh weight, and easy to use. It have a custom config, with a possibility to see DEBUG messages about how plugin is sending packets, what he is reciving with a very clear information for user about what's wrong with his code.

For now, it contains only:
3 Conditions
3 Effects
3 Expressions
But in the future releases i want to add more syntaxes, for the first release skScraft have the most demanded features.

Skript Hub Username: scraft_official
Addon name: skScraft
Link to addon: https://github.com/scraft-official/skScraft

I will add my Addon, to more pages in few days (like spigot), but for now i have made a GitHub project, with great instructions, how to use skScraft.

Dependency: BungeeBridge

**Comment by eyesniper2** [comment]
Awesome! skScraft has been added to your account!
