### ISSUE TITLE
New Add-on c:

### ISSUE THREAD

**Issue by Ankoki** [SkriptHub/SkriptHub#56]
Skript Hub Username: Ankoki
Addon name: SkJade
link to addon: https://forums.skunity.com/resources/skjade.1267/ (if that doesn't work, https://www.spigotmc.org/resources/skript-addon-skjade.89127/ or https://www.github.com/Ankoki-Dev/SkJade)
Thank you c:

**Comment by eyesniper2** [comment]
Awesome! SkJade has been added to your account!
