### ISSUE TITLE
New Addon

### ISSUE THREAD

**Issue by ItsTheSky** [SkriptHub/SkriptHub#58]
Hello 👋
I'm requesting for new addon, yes in know another one 😂
DiSky can link Discodd and Skript. e.g. it's a whole remake, from starting, of Vixio. I already done some quite basics work so you can feedback it 😅
Always under alpha state and could have some bugs, however I totally understand if you don't want to add it, since it's not a stable version and there's not a lot of features like Vixio 😄
GitHub link: https://github.com/SkyCraft78/DiSky
(SkriprHub name: SkyCraft78)

**Comment by eyesniper2** [comment]
Awesome! DiSky has been added to your account!
