### ISSUE TITLE
New Addon

### ISSUE THREAD

**Issue by msgdw** [SkriptHub/SkriptHub#59]
Skript Hub Username: msg_dw
Addon name: McQQBot
link to addon: https://gitee.com/msg_dw/McQQBot-Skript/releases

**Comment by eyesniper2** [comment]
Hey I just took a look at the repo and noticed that most of the descriptions were not in English, but the syntax was. Would it be possible for you to translate them to English before I add the addon?

Thanks!

**Comment by msgdw** [comment]
> Hey I just took a look at the repo and noticed that most of the descriptions were not in English, but the syntax was. Would it be possible for you to translate them to English before I add the addon?
> 
> Thanks!

I think Chinese is more suitable for its user base,

**Comment by eyesniper2** [comment]
Okay, would it be possible to provide both English and Chinese descriptions?

**Comment by msgdw** [comment]
> Okay, would it be possible to provide both English and Chinese descriptions?

no problem

**Comment by eyesniper2** [comment]
Awesome! McQQBot has been added to your account!
