### ISSUE TITLE
Can't Open Documentation, HTTP 404

### ISSUE THREAD

**Issue by qsef1256** [SkriptHub/SkriptHub#65]
![image](https://user-images.githubusercontent.com/44014066/121157947-f2391e80-c884-11eb-931f-3e2ed59b0fe8.png)

Failed to load resource: the server responded with a status of 404 (
main.e6030898.css:1 Failed to load resource: the server responded with a status of 404 ()
main.ed50fd37.js:1 Failed to load resource: the server responded with a status of 404 ()
main.e6030898.css:1 Failed to load resource: the server responded with a status of 404 ()

The documentation site could not be opened with a 404 error. I have the same problem on my smartphone. Could you confirm this issue? Thank you.

**Comment by eyesniper2** [comment]
Thanks for the heads up, I have a build spinning up that will fix this. I will post here again once fixed.

**Comment by eyesniper2** [comment]
Following up, this has been fixed. Thanks for the heads up!
