### ISSUE TITLE
New Addon

### ISSUE THREAD

**Issue by tarna** [SkriptHub/SkriptHub#72]
Skript Hub Username: Tarna256
Addon name: SkMore
link to addon: https://github.com/tarna/SkMore

**Comment by eyesniper2** [comment]
Hey Tarna,

Is there a place where people can download the plugin? It doesnt look like there are any releases on your github yet.

**Comment by tarna** [comment]
> Hey Tarna,
> 
> Is there a place where people can download the plugin? It doesnt look like there are any releases on your github yet.

Hey sorry, there should be one there now. I just made the repo and it was just uploaded so it probably wasn't finished when you checked.

**Comment by eyesniper2** [comment]
Awesome! SkMore has been added to your account!
