### ISSUE TITLE
New Addon: skript-storage

### ISSUE THREAD

**Issue by ItsTheSky** [SkriptHub/SkriptHub#77]
Hello 😄 

Is it possible to add [skript-storage](https://github.com/SkyCraft78/skript-storage) to SkriptHub's docs ?
My user name is `SkyCraft78`
Latest release link: https://github.com/SkyCraft78/skript-storage/releases/tag/1.0.0

Oh and by the way, is it possible to completely remove DiSky (docs + its instance in the docs, aka the addon from my account) from SkriptHub, please?

Thank you in advance,
Regards, Sky ^^

**Comment by eyesniper2** [comment]
Awesome! skript-storage has been added to your account! I will DM you on discord to start the process from removing DiSky.
