### ISSUE TITLE
https://skripthub.net/docs/?id=2113 (Ceil function) has incorrect description

### ISSUE THREAD

**Issue by Xicad** [SkriptHub/SkriptHub#78]
The description says "Rounds a number down, i.e. returns the closest integer larger than or equal to the argument."

It should be "Rounds a number up, i.e. returns the closest integer larger than or equal to the argument."

**Comment by eyesniper2** [comment]
Thanks for the heads up, it appears to have been an issue with Skript generated docs in the past. I have gone and updated all the docs to the latest release (2.6).
