### ISSUE TITLE
im so sorry to waste your time

### ISSUE THREAD

**Issue by Splixey** [SkriptHub/SkriptHub#80]
I am just confused on how to make it like so when doing /spawn it faces you a different way then the default way..if that makes sense?

so say when I run /spawn it takes me to the /setspawn location and face south...how would I make it so I would face north instead?

**Comment by eyesniper2** [comment]
Hey @Splixey,

Unfortunately this isn't the place for Skript support. You should be able to get help in our discord for Skript related issues in the skript-help channel.
