### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ssplixey** [SkriptHub/SkriptHub#81]
I upgraded the uh server plan on "minehut" and it says:

[Tue, 15. Mar 2022 00:35:42 GMT ERROR] #!#! [Skript] Severe Error:
[Tue, 15. Mar 2022 00:35:42 GMT ERROR] #!#!
[Tue, 15. Mar 2022 00:35:42 GMT ERROR] #!#! Something went horribly wrong with Skript.
[Tue, 15. Mar 2022 00:35:42 GMT ERROR] #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[Tue, 15. Mar 2022 00:35:42 GMT ERROR] #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[Tue, 15. Mar 2022 00:35:42 GMT ERROR] #!#! Here is full list of them:
[Tue, 15. Mar 2022 00:35:42 GMT ERROR] #!#! skRayFall v1.9.26 (https://sk.rayfall.net/) DiscordSRV v1.23.0 (https://github.com/DiscordSRV/DiscordSRV)
[Tue, 15. Mar 2022 00:35:42 GMT ERROR] #!#! We could not identify which of those are specially related, so this might also be Skript issue.

I am not sure what to do, it's mainly with rayfall and ruins half of my skripts....

**Comment by ssplixey** [comment]
before I upgraded the plan it was working fine

**Comment by eyesniper2** [comment]
Hey @ssplixey,

Unfortunately this isn't the place for skRayFall support. skRayFall issues can be logged here: https://github.com/eyesniper2/skRayFall

However it doesn't look like there is anything related to skRayFall in the stack trace and I suspect this might be a issue with your service provider. Try restarting the server or contact their support.
