### ISSUE TITLE
Addon Deletion

### ISSUE THREAD

**Issue by UnderscoreTud** [SkriptHub/SkriptHub#86]
I would like to delete my addon skript-light as I uploaded kind of as a joke and I don't think it should still stay on SkriptHub.

Skript Hub Username: _tud
Addon name: skript-light
 link to addon:  [SkriptHub](https://skripthub.net/docs/?addon=skript-light) || [Spigot](https://www.spigotmc.org/resources/skript-light.101052/) (Probably going to be deleted soon too)

**Comment by eyesniper2** [comment]
Sounds good, I have removed the addon from your account and the website.
