### ISSUE TITLE
Document `cause exception` effect

### ISSUE THREAD

**Issue by lilrosalyn** [SkriptHub/SkriptHub#89]
Skript has a [(fairly unknown) effect](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffExceptionDebug.java) with the syntax `cause exception` which generates a standard Skript exception.

This effect is nowhere to be found on the SkriptHub site. May this be added to the list of effects?

**Comment by UnderscoreTud** [comment]
The effect is annotated with `@NoDoc` meaning that no docs are generated for said element. It's not skripthub's fault
