### ISSUE TITLE
Attempting to upload JSON import

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptHub/SkriptHub#93]
JSON Error, your syntax was not updated. Please contact support if this issue persists
[Khoryl.zip](https://github.com/SkriptHub/SkriptHub/files/8984723/Khoryl.zip)
.json is zipped in this, potentially too long to process? but yet it displays all the new syntaxes it will add. @eyesniper2

**Comment by eyesniper2** [comment]
Thanks for the heads up and sorry about the delayed response,

I took a look, and it appears that "Set Steerable Saddle" and "Set Strider Shivering" both share the same JSON id of "SetCharging". If you generated this via the Skript Hub Docs Tool there might have been a message about a ID conflict being unable to be resolved.

To fix this, you can use the ```@DocumentationId("NewDocumentationID")``` annotation in you code and regenerate the docs or you can manually change the id in the JSON file as a short term fix.

I'm going to revisit how I handle conflicting ID merging and see how I can make that system a bit more robust to prevent these issues in the future.

**Comment by TheLimeGlass** [comment]
Can you also make the website display a message stating why it error?
