### ISSUE TITLE
New Addon

### ISSUE THREAD

**Issue by Deglam** [SkriptHub/SkriptHub#94]
Skript Hub Username: Deglam
Addon name: SkEvent
Link to addon: https://www.mediafire.com/file/cyb17xdw9d06ip8/SkEvent.jar/file

**Comment by eyesniper2** [comment]
Is there a more permanent page for this addon vs just a media fire link?

**Comment by Deglam** [comment]
https://www.spigotmc.org/resources/skevent-skript-addon-forcejump-border-size.103275/
