### ISSUE TITLE
Discord Login is broken

### ISSUE THREAD

**Issue by UnderscoreTud** [SkriptHub/SkriptHub#99]
Hey, I'm trying to login to my SkriptHub account using discord, but it sends me to this page
![image](https://user-images.githubusercontent.com/98935832/183530104-968024ff-42a7-4ddf-a666-372ef07494d0.png)

**Comment by eyesniper2** [comment]
Thanks for the heads up! I'll take a look tonight at this and see what happened.

**Comment by eyesniper2** [comment]
Following up, this issue should be fixed now. Thanks for reporting it!
